Repository AbdElrhmanJabr/abood-basel, pull requests merged in 2023-02, with the labels that each got.

#2 fix class name
  style.css
Labels: wating-review

#5 fixed
  index.html
Labels: good first issue

#6 fixed class name
  index.html
Labels: waiting review
